global:
  resolve_timeout: 5m

  # E-Mail SMTP Settings
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'yourmail@gmail.com'
  smtp_auth_username: 'yourmail@gmail.com'
  smtp_auth_password: 'YOUR_SMTP_APP_PASSWORT'

route:
  receiver: 'slack'
  routes:
    - match:
        alertname: DeadMansSwitch
      receiver: 'telegram'
    - match:
        severity: critical
      receiver: 'email'
    - match:
        severity: warning
      receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/DEINE/SLACK/WEBHOOK'
        channel: '#alerts'
        title: "{{ .CommonAnnotations.summary }}"
        text: |
          *Alert:* {{ .CommonAnnotations.description }}
          *Status:* {{ .Status }}
          *Instance:* {{ .Labels.instance }}

  - name: 'telegram'
    telegram_configs:
      - bot_token: 'DEIN_TELEGRAM_BOT_TOKEN'
        chat_id: 'DEIN_CHAT_ID'
        send_resolved: true
        message: |
          *Alert*
          {{ .CommonAnnotations.summary }}
          Status: {{ .Status }}
          Instance: {{ .Labels.instance }}

  - name: 'email'
    email_configs:
      - to: 'DEIN_EMPFAENGER@gmail.com'
        from: 'DEINMAILACCOUNT@gmail.com'
        send_resolved: true

